/*
 * ELEVATION RISING — Token Economy Page
 * Deep dive into SOT, SUG, SST — the three-token Sotilitarian architecture
 * Interactive flow diagram, tokenomics tables, revenue distribution visualization
 */
import Navigation from "@/components/Navigation";
import SEOHead from "@/components/SEOHead";
import Footer from "@/components/Footer";
import { Link } from "wouter";
import { ArrowRight, ExternalLink, Github, TrendingUp, Shield, Users, Zap, Lock, BarChart3, Coins } from "lucide-react";
import {
  Chart as ChartJS,
  ArcElement,
  Tooltip,
  Legend,
  CategoryScale,
  LinearScale,
  BarElement,
} from "chart.js";
import { Doughnut, Bar } from "react-chartjs-2";

ChartJS.register(ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement);

const GITHUB_CONTRACTS = "https://github.com/ModernDigitalDevelopment/sotilitarianism/tree/main/smart-contracts/contracts";

// Revenue distribution donut data
const revenueData = {
  labels: ["SOT Dividends (40%)", "SST Reserves (40%)", "SUG Community (20%)"],
  datasets: [
    {
      data: [40, 40, 20],
      backgroundColor: [
        "rgba(201,168,76,0.85)",
        "rgba(255,255,255,0.25)",
        "rgba(77,184,184,0.85)",
      ],
      borderColor: [
        "rgba(201,168,76,1)",
        "rgba(255,255,255,0.5)",
        "rgba(77,184,184,1)",
      ],
      borderWidth: 2,
      hoverOffset: 8,
    },
  ],
};

const revenueOptions = {
  responsive: true,
  maintainAspectRatio: true,
  plugins: {
    legend: {
      position: "bottom" as const,
      labels: {
        color: "rgba(255,255,255,0.7)",
        font: { family: "'DM Sans', sans-serif", size: 12 },
        padding: 16,
        usePointStyle: true,
      },
    },
    tooltip: {
      callbacks: {
        label: (ctx: any) => ` ${ctx.label}`,
      },
    },
  },
};

// Token utility comparison bar chart
const utilityData = {
  labels: ["SOT", "SUG", "SST"],
  datasets: [
    {
      label: "Governance Weight",
      data: [90, 60, 10],
      backgroundColor: "rgba(201,168,76,0.7)",
      borderColor: "rgba(201,168,76,1)",
      borderWidth: 1,
    },
    {
      label: "Yield Generation",
      data: [85, 30, 40],
      backgroundColor: "rgba(77,184,184,0.7)",
      borderColor: "rgba(77,184,184,1)",
      borderWidth: 1,
    },
    {
      label: "Stability",
      data: [20, 10, 100],
      backgroundColor: "rgba(255,255,255,0.2)",
      borderColor: "rgba(255,255,255,0.5)",
      borderWidth: 1,
    },
  ],
};

const utilityOptions = {
  responsive: true,
  maintainAspectRatio: true,
  plugins: {
    legend: {
      position: "top" as const,
      labels: {
        color: "rgba(255,255,255,0.7)",
        font: { family: "'DM Sans', sans-serif", size: 11 },
        padding: 12,
        usePointStyle: true,
      },
    },
  },
  scales: {
    x: {
      ticks: { color: "rgba(255,255,255,0.6)", font: { family: "'Courier Prime', monospace", size: 12 } },
      grid: { color: "rgba(255,255,255,0.05)" },
    },
    y: {
      max: 100,
      ticks: {
        color: "rgba(255,255,255,0.4)",
        font: { family: "'Courier Prime', monospace", size: 10 },
        callback: (v: any) => `${v}%`,
      },
      grid: { color: "rgba(255,255,255,0.05)" },
    },
  },
};

const tokens = [
  {
    symbol: "SOT",
    name: "SotilityOwnershipToken",
    tagline: "Ownership · Governance · Dividends",
    color: "text-gold",
    border: "border-gold/40",
    bg: "bg-gold/10",
    glow: "glow-gold",
    supply: "1,000,000,000",
    supplyLabel: "Fixed Supply",
    icon: TrendingUp,
    description: "SOT is the equity layer of the Sotilitarian ecosystem. It represents ownership in the Elevation Foundation's protocol revenue. Every dollar generated by the Elevation Engine flows 40% to SOT holders as automated dividends — no board approval, no human intermediary, just code.",
    mechanics: [
      { label: "Revenue Share", value: "40% of all protocol revenue", icon: BarChart3 },
      { label: "Voting Power", value: "1 SOT = 1 governance vote", icon: Users },
      { label: "Staking Yield", value: "Additional yield via Elevation Engine", icon: TrendingUp },
      { label: "Vesting", value: "Time-locked schedules prevent power concentration", icon: Lock },
    ],
    contract: "SotilityOwnershipToken.sol",
  },
  {
    symbol: "SUG",
    name: "SoGoodUtilityGovernance Token",
    tagline: "Earned · Community · Social Utility",
    color: "text-teal",
    border: "border-teal/40",
    bg: "bg-teal/10",
    glow: "glow-teal",
    supply: "Earned, Not Purchased",
    supplyLabel: "Contribution-Based",
    icon: Users,
    description: "SUG cannot be bought — it must be earned through verified contributions on the SoGood social platform. This is the utility layer: your positive actions in the community generate real economic yield. SUG is the proof that social good and financial return are not opposites.",
    mechanics: [
      { label: "Distribution", value: "20% of protocol revenue to community campaigns", icon: Coins },
      { label: "Earning", value: "Verified contributions on SoGood platform", icon: Zap },
      { label: "Time-Lock", value: "Long-term participation is rewarded over speculation", icon: Lock },
      { label: "Uses", value: "Proposal weighting, content curation, tipping", icon: Shield },
    ],
    contract: "SoGoodUtilityGovernance.sol",
  },
  {
    symbol: "SST",
    name: "SotilityStableToken",
    tagline: "USD-Pegged · Revenue-Backed · Auditable",
    color: "text-white/85",
    border: "border-white/30",
    bg: "bg-white/5",
    glow: "",
    supply: "1:1 Revenue Backed",
    supplyLabel: "Dynamic Supply",
    icon: Shield,
    description: "SST is a USD-pegged stablecoin with a fundamental difference from every other stablecoin: it is minted against verified organizational efficiency gains, not stored wealth. When an organization adopts Sotility Trust Tech and proves measurable efficiency surplus, they can mint SST — creating money from demonstrated improvement.",
    mechanics: [
      { label: "Peg", value: "1:1 USD backed by verified business revenue", icon: Shield },
      { label: "Audit Trail", value: "Every mint backed by IPFS receipt", icon: Lock },
      { label: "Reserve", value: "40% of protocol revenue maintains SST reserves", icon: BarChart3 },
      { label: "Use Cases", value: "Treasury, payroll, cross-border payments", icon: Coins },
    ],
    contract: "SotilityStableToken.sol",
  },
];

const flywheel = [
  { step: "01", title: "Elevation Engine generates yield", desc: "AI-managed DeFi strategies generate protocol revenue autonomously, 24/7." },
  { step: "02", title: "Revenue distributed by smart contract", desc: "SotilityTreasuryRouter automatically splits: 40% SOT dividends · 40% SST reserves · 20% SUG campaigns." },
  { step: "03", title: "SOT holders receive dividends", desc: "Token holders earn passive income proportional to their stake — no claiming required." },
  { step: "04", title: "SUG rewards community action", desc: "Real-world contributions on SoGood earn SUG tokens, creating an economic incentive for social good." },
  { step: "05", title: "SST stabilizes the ecosystem", desc: "Verified efficiency surpluses are minted into SST, creating a self-sustaining monetary supply that grows with adoption." },
  { step: "06", title: "Revenue grows, cycle repeats", desc: "More adoption → more revenue → more dividends → more contributors → more adoption. A genuine virtuous cycle." },
];

export default function TokenEconomy() {
  return (
    <div className="min-h-screen bg-navy text-white">
      <SEOHead
        title="Three-Token Economy | SOT · SUG · SST | The Elevation Foundation"
        description="The Sotilitarian three-token economy: SOT (ownership + dividends), SUG (social utility + governance), SST (USD-pegged stablecoin). Learn how protocol revenue is distributed automatically — 40% to SOT, 40% to SST, 20% to SUG community campaigns."
        canonical="/token-economy"
        keywords="SOT token, SUG token, SST stablecoin, Sotilitarian tokenomics, three-token economy, blockchain governance tokens, community dividends, social utility token, DeFi stablecoin, Elevation Foundation, Sotilitarianism"
      />
      <Navigation />

      {/* Hero */}
      <section className="relative pt-32 pb-20 overflow-hidden">
        <div
          className="absolute inset-0 opacity-10"
          aria-hidden="true"
          style={{
            backgroundImage: "radial-gradient(circle at 1px 1px, oklch(0.72 0.12 75) 1px, transparent 0)",
            backgroundSize: "36px 36px",
          }}
        />
        <div className="absolute inset-0 bg-gradient-to-b from-navy/40 via-transparent to-navy" />
        <div className="container relative z-10 text-center">
          <div className="section-label mb-4">Token Economy</div>
          <h1 className="font-display text-5xl md:text-7xl font-black text-white leading-tight mb-6">
            Three Tokens.
            <br />
            <span className="gold-shimmer">One Ecosystem.</span>
          </h1>
          <p className="font-body text-xl text-white/65 max-w-3xl mx-auto leading-relaxed mb-10">
            The Sotilitarian three-token architecture creates a self-sustaining loop where governance, social utility, and monetary stability reinforce each other — entirely governed by smart contracts, with zero human intermediaries in the revenue flow.
          </p>
          <div className="flex flex-wrap gap-4 justify-center">
            <a
              href={GITHUB_CONTRACTS}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-6 py-3 border border-white/20 text-white/70 font-body text-sm rounded-sm hover:border-gold/40 hover:text-gold transition-all duration-200"
            >
              <Github size={16} /> View Smart Contracts
            </a>
            <Link
              href="/philosophy"
              className="inline-flex items-center gap-2 px-6 py-3 bg-gold text-[oklch(0.12_0.05_265)] font-body font-semibold text-sm rounded-sm hover:bg-gold-light transition-all duration-200 group"
            >
              Full Philosophy <ArrowRight size={14} className="group-hover:translate-x-1 transition-transform" />
            </Link>
          </div>
        </div>
      </section>

      {/* Revenue Distribution Visual */}
      <section className="py-20 bg-[oklch(0.14_0.05_265)]">
        <div className="container">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <div>
              <div className="section-label mb-3">Revenue Architecture</div>
              <h2 className="font-display text-4xl font-bold text-white mb-6">
                Every Dollar, <span className="text-gold">Accounted For</span>
              </h2>
              <p className="font-body text-white/65 text-lg leading-relaxed mb-6">
                Protocol revenue from the Elevation Engine is not managed by a board or subject to a vote. It is split automatically by the <strong className="text-white">SotilityTreasuryRouter</strong> smart contract — every single time, with full on-chain transparency.
              </p>
              <div className="space-y-4 mb-8">
                {[
                  { pct: "40%", label: "SOT Dividends", desc: "Paid directly to SOT token holders", color: "bg-gold" },
                  { pct: "40%", label: "SST Reserves", desc: "Maintains SST stablecoin peg and ecosystem stability", color: "bg-white/30" },
                  { pct: "20%", label: "SUG Community", desc: "Funds community campaigns and social good rewards", color: "bg-teal" },
                ].map((item) => (
                  <div key={item.label} className="flex items-center gap-4 p-4 bg-[oklch(0.16_0.05_265)] border border-white/10 rounded-sm">
                    <div className={`w-12 h-12 flex-shrink-0 flex items-center justify-center rounded-sm ${item.color} text-[oklch(0.12_0.05_265)] font-bold font-display text-sm`}>
                      {item.pct}
                    </div>
                    <div>
                      <div className="font-body font-semibold text-white text-sm">{item.label}</div>
                      <div className="font-body text-white/50 text-xs">{item.desc}</div>
                    </div>
                  </div>
                ))}
              </div>
              <div className="p-4 border border-gold/20 bg-gold/5 rounded-sm">
                <p className="font-mono-data text-xs text-gold/70 uppercase tracking-wider mb-1">On-chain contract</p>
                <p className="font-body text-white/60 text-sm">SotilityTreasuryRouter.sol — autonomous distribution, no human approval required. View on GitHub.</p>
              </div>
            </div>
            <div className="max-w-sm mx-auto w-full">
              <div className="bg-[oklch(0.16_0.05_265)] border border-white/10 rounded-sm p-8">
                <div className="font-mono-data text-xs text-gold/60 uppercase tracking-wider text-center mb-6">Protocol Revenue Split</div>
                <Doughnut data={revenueData} options={revenueOptions} />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Token utility comparison */}
      <section className="py-20 bg-navy">
        <div className="container">
          <div className="text-center mb-12">
            <div className="section-label mb-3">Token Utility Matrix</div>
            <h2 className="font-display text-4xl font-bold text-white">
              Three Tokens. <span className="text-gold">Three Purposes.</span>
            </h2>
            <p className="font-body text-white/55 mt-4 max-w-2xl mx-auto">Each token excels in its lane. Together they cover governance, social utility, and monetary stability — the three pillars of the Sotilitarian architecture.</p>
          </div>
          <div className="max-w-2xl mx-auto bg-[oklch(0.16_0.05_265)] border border-white/10 rounded-sm p-8">
            <Bar data={utilityData} options={utilityOptions} />
          </div>
        </div>
      </section>

      {/* Individual token deep-dives */}
      <section className="py-20 bg-[oklch(0.14_0.05_265)]">
        <div className="container">
          <div className="text-center mb-14">
            <div className="section-label mb-3">Token Architecture</div>
            <h2 className="font-display text-4xl font-bold text-white">
              Deep Dive: <span className="text-gold">The Three Tokens</span>
            </h2>
          </div>
          <div className="space-y-12">
            {tokens.map((token) => {
              const IconComp = token.icon;
              return (
                <div
                  key={token.symbol}
                  className={`bg-[oklch(0.16_0.05_265)] border ${token.border} rounded-sm overflow-hidden`}
                >
                  <div className={`${token.bg} px-8 py-6 border-b ${token.border}`}>
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                      <div className="flex items-center gap-4">
                        <div className={`w-14 h-14 flex items-center justify-center rounded-sm border ${token.border} ${token.bg}`}>
                          <span className={`font-mono-data text-lg font-bold ${token.color}`}>{token.symbol}</span>
                        </div>
                        <div>
                          <div className={`font-mono-data text-xs uppercase tracking-widest mb-0.5 ${token.color}`}>{token.tagline}</div>
                          <div className="font-display text-xl font-bold text-white">{token.name}</div>
                        </div>
                      </div>
                      <div className="text-right">
                        <div className="font-mono-data text-xs text-white/35 uppercase mb-0.5">{token.supplyLabel}</div>
                        <div className={`font-display text-lg font-bold ${token.color}`}>{token.supply}</div>
                      </div>
                    </div>
                  </div>
                  <div className="p-8">
                    <p className="font-body text-white/70 text-base leading-relaxed mb-8">{token.description}</p>
                    <div className="grid sm:grid-cols-2 gap-4 mb-6">
                      {token.mechanics.map((m) => {
                        const MIcon = m.icon;
                        return (
                          <div key={m.label} className="flex items-start gap-3 p-4 bg-[oklch(0.14_0.05_265)] rounded-sm border border-white/5">
                            <MIcon size={16} className={`mt-0.5 flex-shrink-0 ${token.color}`} />
                            <div>
                              <div className={`font-body font-semibold text-xs uppercase tracking-wide mb-1 ${token.color}`}>{m.label}</div>
                              <div className="font-body text-white/55 text-sm leading-relaxed">{m.value}</div>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                    <a
                      href={`${GITHUB_CONTRACTS}/${token.contract}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className={`inline-flex items-center gap-2 font-mono-data text-xs uppercase tracking-wider ${token.color} hover:opacity-80 transition-opacity`}
                    >
                      <Github size={13} /> {token.contract} <ExternalLink size={11} />
                    </a>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Flywheel */}
      <section className="py-24 bg-navy relative overflow-hidden">
        <div
          className="absolute inset-0 opacity-5"
          aria-hidden="true"
          style={{
            backgroundImage: "radial-gradient(circle at 2px 2px, oklch(0.72 0.12 75) 1px, transparent 0)",
            backgroundSize: "40px 40px",
          }}
        />
        <div className="container relative z-10">
          <div className="text-center mb-14">
            <div className="section-label mb-3">Economic Architecture</div>
            <h2 className="font-display text-4xl font-bold text-white">
              The <span className="text-gold">Virtuous Flywheel</span>
            </h2>
            <p className="font-body text-white/55 mt-4 max-w-2xl mx-auto">
              Each token feeds into the next. Revenue generates dividends, dividends attract holders, activity generates utility, utility mints stability. The flywheel never stops.
            </p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {flywheel.map((step, i) => (
              <div
                key={step.step}
                className="relative bg-[oklch(0.16_0.05_265)] border border-white/10 p-6 rounded-sm card-lift"
              >
                <div className="font-mono-data text-3xl font-bold text-gold/20 mb-3">{step.step}</div>
                <h3 className="font-display text-lg font-bold text-white mb-2">{step.title}</h3>
                <p className="font-body text-white/55 text-sm leading-relaxed">{step.desc}</p>
                {i < flywheel.length - 1 && (
                  <div className="absolute -right-3 top-1/2 -translate-y-1/2 hidden lg:block z-10">
                    <ArrowRight size={18} className="text-gold/30" />
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 bg-[oklch(0.14_0.05_265)]">
        <div className="container text-center">
          <h2 className="font-display text-4xl font-bold text-white mb-4">
            Ready to <span className="text-gold">Explore the Architecture?</span>
          </h2>
          <p className="font-body text-white/60 text-lg max-w-2xl mx-auto mb-8">
            Every smart contract is public, auditable, and open source. The governance model is fully documented. There are no closed doors in the Sotilitarian ecosystem.
          </p>
          <div className="flex flex-wrap gap-4 justify-center">
            <a
              href={GITHUB_CONTRACTS}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-7 py-3.5 border border-white/20 text-white/70 font-body font-medium rounded-sm hover:border-gold/40 hover:text-gold transition-all duration-200"
            >
              <Github size={16} /> View All Contracts
            </a>
            <Link
              href="/philosophy"
              className="inline-flex items-center gap-2 px-7 py-3.5 bg-gold text-[oklch(0.12_0.05_265)] font-body font-semibold rounded-sm hover:bg-gold-light transition-all duration-200 group"
            >
              Full Philosophy <ArrowRight size={14} className="group-hover:translate-x-1 transition-transform" />
            </Link>
            <Link
              href="/white-papers"
              className="inline-flex items-center gap-2 px-7 py-3.5 border border-gold/30 text-gold font-body font-medium rounded-sm hover:bg-gold/10 transition-all duration-200"
            >
              Read the Whitepapers
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
