/**
 * WeSolar — Dedicated Project Page
 * Covers: mission, how it works, 4 smart contracts, Celo grant, waitlist signup
 */
import { useState } from "react";
import { Link } from "wouter";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import SEOHead from "@/components/SEOHead";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Sun, Zap, Users, Vote, ExternalLink, Github, CheckCircle2, Leaf, Globe, TrendingUp } from "lucide-react";
import { toast } from "sonner";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Filler,
  Tooltip,
  Legend,
} from "chart.js";
import { Line } from "react-chartjs-2";

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Filler, Tooltip, Legend);

// ─── Energy Adoption Chart ───────────────────────────────────────────────────
const YEARS = ["2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030"];

const adoptionChartData = {
  labels: YEARS,
  datasets: [
    {
      label: "Community Solar Adoption (% of eligible households)",
      data: [2, 3, 5, 8, 13, 20, 30, 43, 57, 70, 81],
      borderColor: "#4db8b8",
      backgroundColor: "rgba(77,184,184,0.12)",
      fill: true,
      tension: 0.45,
      pointRadius: 4,
      pointBackgroundColor: "#4db8b8",
      borderWidth: 2.5,
    },
    {
      label: "Incumbent Utility Market Share (%)",
      data: [94, 92, 90, 87, 83, 77, 70, 62, 52, 41, 30],
      borderColor: "#c0392b",
      backgroundColor: "rgba(192,57,43,0.08)",
      fill: true,
      tension: 0.45,
      pointRadius: 4,
      pointBackgroundColor: "#c0392b",
      borderWidth: 2.5,
      borderDash: [6, 3],
    },
  ],
};

const adoptionChartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  interaction: { mode: "index" as const, intersect: false },
  plugins: {
    legend: {
      display: true,
      position: "top" as const,
      labels: {
        font: { family: "Courier New, monospace", size: 10 },
        color: "#555",
        padding: 16,
        boxWidth: 12,
      },
    },
    tooltip: {
      backgroundColor: "#1a1a2e",
      titleFont: { family: "Georgia, serif", size: 12 },
      bodyFont: { family: "Courier New, monospace", size: 11 },
      padding: 10,
      callbacks: {
        label: (ctx: any) => ` ${ctx.dataset.label}: ${ctx.raw}%`,
      },
    },
  },
  scales: {
    x: {
      grid: { color: "rgba(0,0,0,0.06)" },
      ticks: { font: { family: "Courier New, monospace", size: 10 }, color: "#666" },
    },
    y: {
      min: 0,
      max: 100,
      grid: { color: "rgba(0,0,0,0.06)" },
      ticks: {
        font: { family: "Courier New, monospace", size: 10 },
        color: "#666",
        callback: (v: any) => `${v}%`,
      },
    },
  },
};

const contracts = [
  {
    name: "WeSolarToken.sol",
    symbol: "WST",
    description: "ERC-20 energy credit token. Residents earn WST for every kilowatt-hour generated by their fractionally owned solar panels. Tradeable peer-to-peer on the WeSolarMarketplace.",
    color: "text-teal",
    border: "border-teal/30",
    bg: "bg-teal/5",
  },
  {
    name: "SolarPanelRegistry.sol",
    symbol: "Registry",
    description: "On-chain registry of every solar panel in the WeSolar network. Records panel ID, location, capacity, owner fractions, and cumulative energy output. The single source of truth for the ecosystem.",
    color: "text-gold",
    border: "border-gold/30",
    bg: "bg-gold/5",
  },
  {
    name: "WeSolarFinancing.sol",
    symbol: "Crowdfund",
    description: "Fractional NFT ownership of solar infrastructure. Community members pool capital to fund panel installations. Each contributor receives an NFT representing their ownership fraction and proportional energy credits.",
    color: "text-crimson",
    border: "border-crimson/30",
    bg: "bg-crimson/5",
  },
  {
    name: "WeSolarDAO.sol",
    symbol: "Governance",
    description: "Community governance for expansion decisions. WST holders vote on new installation locations, energy credit pricing, treasury allocations, and protocol upgrades. No board. No executives. Just token-weighted democracy.",
    color: "text-white/80",
    border: "border-white/20",
    bg: "bg-white/5",
  },
];

const howItWorks = [
  {
    step: "01",
    icon: Users,
    title: "Community Pools Capital",
    desc: "Residents contribute as little as $50 to fund a solar panel installation in their neighborhood. Each contributor receives a fractional NFT representing their ownership stake.",
    color: "text-gold",
  },
  {
    step: "02",
    icon: Sun,
    title: "Panels Generate Energy",
    desc: "Installed panels generate electricity. Smart meters report output to the SolarPanelRegistry on-chain. The WeSolarToken contract automatically mints WST credits proportional to each owner's fraction.",
    color: "text-teal",
  },
  {
    step: "03",
    icon: Zap,
    title: "Earn & Trade Credits",
    desc: "WST energy credits can be redeemed against utility bills, traded peer-to-peer on the WeSolarMarketplace, or staked in the DAO treasury to earn governance weight.",
    color: "text-crimson",
  },
  {
    step: "04",
    icon: Vote,
    title: "Vote on Expansion",
    desc: "The community votes on where to install the next panels, how to price credits, and how to deploy treasury funds. Every decision is recorded on-chain and publicly verifiable.",
    color: "text-gold",
  },
];

const stats = [
  { value: "4", label: "Smart Contracts" },
  { value: "IOTA", label: "Feeless Tangle Settlement" },
  { value: "$25K–$100K", label: "Celo Grant Target" },
  { value: "501(c)(3)", label: "Nonprofit Infrastructure" },
];

export default function WeSolar() {
  const [email, setEmail] = useState("");
  const [firstName, setFirstName] = useState("");
  const [submitted, setSubmitted] = useState(false);

  const subscribe = trpc.newsletter.subscribe.useMutation({
    onSuccess: (data) => {
      if (data.alreadySubscribed) {
        toast.info("You're already on the WeSolar waitlist. We'll be in touch!");
      } else {
        toast.success("You're on the waitlist! We'll notify you when WeSolar launches in your area.");
        setSubmitted(true);
      }
      setEmail("");
      setFirstName("");
    },
    onError: (err) => {
      toast.error(err.message || "Something went wrong. Please try again.");
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!email) return;
    subscribe.mutate({ email, firstName: firstName || undefined, source: "wesolar" });
  };

  return (
    <div className="min-h-screen bg-navy text-white">
      <SEOHead
        title="WeSolar — Community-Owned Solar Energy | The Elevation Foundation"
        description="WeSolar is a decentralized peer-to-peer solar financing platform. Residents co-own solar infrastructure through fractional NFT ownership, earn energy credits, and vote on expansion — all governed by smart contracts on the IOTA Tangle."
        keywords="WeSolar, community solar, fractional solar ownership, IOTA Tangle, energy credits, WeSolarToken, WST, decentralized energy, Celo Climate Collective, community-owned solar, tokenized solar panels"
      />
      <Navigation />

      {/* ─── HERO ─────────────────────────────────────────────── */}
      <section className="relative min-h-[70vh] flex items-center overflow-hidden pt-20">
        <div className="absolute inset-0 bg-gradient-to-br from-[oklch(0.10_0.05_265)] via-[oklch(0.12_0.08_160/0.4)] to-[oklch(0.10_0.05_265)]" />
        {/* Decorative sun */}
        <div className="absolute top-20 right-10 md:right-32 w-64 h-64 rounded-full bg-gradient-to-br from-[oklch(0.72_0.12_75/0.15)] to-[oklch(0.55_0.14_160/0.08)] blur-3xl" />
        <div className="absolute top-24 right-14 md:right-36 w-48 h-48 rounded-full border border-gold/20" />
        <div className="absolute top-28 right-18 md:right-40 w-36 h-36 rounded-full border border-gold/10" />

        <div className="container relative z-10 py-20">
          <div className="max-w-3xl">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 bg-teal/10 border border-teal/30 rounded-sm mb-6">
              <Leaf size={12} className="text-teal" />
              <span className="font-mono-data text-xs text-teal tracking-wider uppercase">Community Solar · IOTA Tangle · Celo Climate Collective</span>
            </div>
            <h1 className="font-display text-5xl md:text-7xl font-black leading-[1.05] mb-6">
              <span className="text-white">We</span>
              <span className="text-teal">Solar</span>
              <br />
              <span className="text-white/70 text-4xl md:text-5xl italic font-light">Energy Owned by the People Who Use It.</span>
            </h1>
            <p className="font-body text-lg md:text-xl text-white/75 leading-relaxed mb-10 max-w-2xl">
              WeSolar is a decentralized peer-to-peer solar financing platform. Residents co-own solar infrastructure through fractional NFT ownership, earn WeSolar Credits for energy generated, and vote on expansion — all governed by smart contracts. No utility company. No bank. Just community.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <a
                href="#waitlist"
                className="inline-flex items-center gap-2 px-7 py-3.5 bg-teal text-[oklch(0.12_0.05_265)] font-semibold font-body rounded-sm hover:bg-teal/90 transition-all duration-200 hover:shadow-[0_0_30px_oklch(0.55_0.14_160/0.4)] group"
              >
                Join the Waitlist
                <ArrowRight size={16} className="group-hover:translate-x-1 transition-transform" />
              </a>
              <a
                href="https://github.com/ModernDigitalDevelopment/wesolar"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-7 py-3.5 border border-white/30 text-white font-body font-medium rounded-sm hover:border-teal/50 hover:text-teal transition-all duration-200"
              >
                <Github size={16} />
                View on GitHub
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* ─── STATS BAR ────────────────────────────────────────── */}
      <section className="bg-[oklch(0.16_0.05_265)] border-y border-white/10 py-8">
        <div className="container">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat) => (
              <div key={stat.label} className="text-center">
                <div className="font-display text-3xl md:text-4xl font-bold text-teal mb-1">{stat.value}</div>
                <div className="font-mono-data text-xs tracking-wider text-white/50 uppercase">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── THE PROBLEM ──────────────────────────────────────── */}
      <section className="py-24 bg-navy">
        <div className="container">
          <div className="grid md:grid-cols-2 gap-16 items-center">
            <div>
              <div className="section-label mb-4">The Problem</div>
              <h2 className="font-display text-4xl md:text-5xl font-bold text-white leading-tight mb-6">
                Energy Poverty Is a
                <br />
                <span className="text-teal italic">Design Choice.</span>
              </h2>
              <p className="font-body text-white/70 text-lg leading-relaxed mb-6">
                Utility companies charge the highest rates to the communities that can least afford them. Solar energy — the most abundant, cheapest energy source on earth — remains inaccessible to low-income households because of high upfront installation costs and a financing system that requires credit scores and collateral.
              </p>
              <p className="font-body text-white/70 text-lg leading-relaxed mb-8">
                WeSolar removes both barriers. Fractional NFT ownership means a household can participate for $50. Smart contract financing means no bank, no credit check, no intermediary taking a cut. The IOTA Tangle's feeless microtransactions make sub-cent energy credit settlements economically viable for the first time.
              </p>
            </div>
            <div className="space-y-4">
              {[
                { label: "Average utility rate increase (2020–2025)", value: "+34%", color: "text-crimson" },
                { label: "US households in energy poverty", value: "~31M", color: "text-gold" },
                { label: "Solar cost reduction (2010–2024)", value: "-90%", color: "text-teal" },
                { label: "Community solar market growth (2023–2028)", value: "+180%", color: "text-teal" },
              ].map((item) => (
                <div key={item.label} className="flex items-center justify-between p-4 bg-[oklch(0.16_0.05_265)] border border-white/10 rounded-sm">
                  <span className="font-body text-sm text-white/60">{item.label}</span>
                  <span className={`font-display text-2xl font-bold ${item.color}`}>{item.value}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ─── ENERGY ADOPTION CHART ────────────────────────────── */}
      <section className="py-20 bg-[oklch(0.14_0.05_265)]" aria-label="Community solar adoption chart">
        <div className="container">
          <div className="max-w-4xl mx-auto">
            {/* Section label */}
            <div className="mb-8 text-center">
              <div className="section-label mb-3">The Inflection Point</div>
              <h2 className="font-display text-3xl md:text-4xl font-bold text-white mb-3">
                Community Solar Is at the <span className="text-teal">S-Curve Knee</span>
              </h2>
              <p className="font-body text-white/55 max-w-xl mx-auto">
                The technology adoption S-curve shows community solar crossing the 50% threshold around 2028 — the same moment incumbent utilities lose majority market share. WeSolar is built to capture that inflection.
              </p>
            </div>

            {/* Chart card — beige background per article style guide */}
            <div style={{
              background: "#f5f0e8",
              borderRadius: "6px",
              padding: "28px 28px 20px",
              border: "1px solid rgba(201,168,76,0.25)",
              marginBottom: "16px",
            }}>
              <div style={{
                fontFamily: "Courier New, monospace",
                fontSize: "0.65rem",
                letterSpacing: "0.12em",
                color: "#c9a84c",
                textTransform: "uppercase" as const,
                marginBottom: "4px",
              }}>
                Figure — Energy Market Adoption Dynamics
              </div>
              <div style={{
                fontFamily: "Georgia, serif",
                fontSize: "1.05rem",
                fontWeight: "700",
                color: "#1a1a2e",
                marginBottom: "4px",
              }}>
                Community Solar Adoption vs. Incumbent Utility Market Share: 2020–2030
              </div>
              <div style={{
                fontFamily: "Georgia, serif",
                fontSize: "0.82rem",
                color: "#555",
                lineHeight: "1.65",
                marginBottom: "20px",
              }}>
                Adoption follows a classic S-curve. The crossover point (~2028) is where community solar protocols like WeSolar become the default infrastructure — not the alternative. Based on NREL community solar growth data and DOE market projections.
              </div>
              <div style={{ height: "320px", position: "relative" }}>
                <Line data={adoptionChartData} options={adoptionChartOptions} />
              </div>
              <div style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                marginTop: "12px",
                paddingTop: "10px",
                borderTop: "1px solid rgba(201,168,76,0.2)",
              }}>
                <span style={{ fontFamily: "Courier New, monospace", fontSize: "0.65rem", color: "#888" }}>
                  Sources: NREL, DOE Solar Energy Technologies Office, Lawrence Berkeley National Lab
                </span>
                <span style={{ fontFamily: "Courier New, monospace", fontSize: "0.65rem", color: "#c9a84c" }}>
                  WeSolar — The Elevation Foundation
                </span>
              </div>
            </div>

            {/* Three callout stats below the chart */}
            <div className="grid grid-cols-3 gap-4">
              {[
                { value: "2028", label: "Projected crossover year", color: "text-teal" },
                { value: "+180%", label: "Community solar growth 2023–2028", color: "text-gold" },
                { value: "31M", label: "US households in energy poverty", color: "text-crimson" },
              ].map(({ value, label, color }) => (
                <div key={label} className="p-4 bg-[oklch(0.16_0.05_265)] border border-white/10 rounded-sm text-center">
                  <div className={`font-display text-2xl font-bold ${color} mb-1`}>{value}</div>
                  <div className="font-mono-data text-[10px] text-white/40 uppercase tracking-wide leading-snug">{label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ─── HOW IT WORKS ─────────────────────────────────────── */}
      <section className="py-24 bg-[oklch(0.14_0.05_265)]">
        <div className="container">
          <div className="text-center mb-14">
            <div className="section-label mb-3">The Mechanism</div>
            <h2 className="font-display text-4xl md:text-5xl font-bold text-white">
              How <span className="text-teal">WeSolar</span> Works
            </h2>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {howItWorks.map(({ step, icon: Icon, title, desc, color }) => (
              <div key={step} className="relative p-7 bg-[oklch(0.16_0.05_265)] border border-white/10 rounded-sm">
                <div className="font-mono-data text-4xl font-bold text-white/10 mb-4">{step}</div>
                <div className={`inline-flex items-center justify-center w-10 h-10 rounded-sm border border-current/30 mb-4 ${color}`}
                  style={{ background: "oklch(0.18 0.05 265)" }}>
                  <Icon size={18} />
                </div>
                <h3 className={`font-display text-lg font-bold mb-3 ${color}`}>{title}</h3>
                <p className="font-body text-sm text-white/60 leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── SMART CONTRACTS ──────────────────────────────────── */}
      <section className="py-24 bg-navy">
        <div className="container">
          <div className="flex flex-col md:flex-row md:items-end justify-between mb-14 gap-4">
            <div>
              <div className="section-label mb-3">Open Source Infrastructure</div>
              <h2 className="font-display text-4xl md:text-5xl font-bold text-white">
                4 Smart Contracts.<br />
                <span className="text-teal">One Ecosystem.</span>
              </h2>
            </div>
            <a
              href="https://github.com/ModernDigitalDevelopment/wesolar/tree/main/contracts"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-white/60 hover:text-teal font-body text-sm transition-colors group"
            >
              <Github size={14} />
              View all contracts
              <ArrowRight size={14} className="group-hover:translate-x-1 transition-transform" />
            </a>
          </div>
          <div className="grid md:grid-cols-2 gap-6">
            {contracts.map((contract) => (
              <div key={contract.name} className={`p-7 border ${contract.border} ${contract.bg} rounded-sm`}>
                <div className="flex items-start justify-between mb-4">
                  <div>
                    <div className={`font-mono-data text-xs tracking-wider uppercase mb-1 ${contract.color}`}>{contract.symbol}</div>
                    <h3 className="font-mono-data text-base font-bold text-white">{contract.name}</h3>
                  </div>
                  <a
                    href={`https://github.com/ModernDigitalDevelopment/wesolar/blob/main/contracts/${contract.name}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className={`${contract.color} hover:opacity-70 transition-opacity`}
                  >
                    <ExternalLink size={14} />
                  </a>
                </div>
                <p className="font-body text-sm text-white/60 leading-relaxed">{contract.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── CELO CLIMATE COLLECTIVE ──────────────────────────── */}
      <section className="py-24 bg-[oklch(0.14_0.05_265)]">
        <div className="container">
          <div className="max-w-3xl mx-auto text-center">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 bg-teal/10 border border-teal/30 rounded-sm mb-6">
              <Globe size={12} className="text-teal" />
              <span className="font-mono-data text-xs text-teal tracking-wider uppercase">Grant Opportunity</span>
            </div>
            <h2 className="font-display text-4xl md:text-5xl font-bold text-white mb-6">
              Celo Climate Collective
              <br />
              <span className="text-teal">$25K–$100K Grant</span>
            </h2>
            <p className="font-body text-white/70 text-lg leading-relaxed mb-8">
              WeSolar is applying to the Celo Climate Collective — a grant program funding blockchain-based climate solutions. Our application demonstrates how WeSolar's tokenized community solar model directly addresses energy poverty in underserved communities while reducing carbon emissions. The full application is published openly on GitHub.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a
                href="https://github.com/ModernDigitalDevelopment/wesolar/blob/main/docs/whitepapers/CELO-CLIMATE-COLLECTIVE-GRANT.md"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-7 py-3.5 bg-teal text-[oklch(0.12_0.05_265)] font-semibold font-body rounded-sm hover:bg-teal/90 transition-all duration-200 group"
              >
                Read the Grant Application
                <ExternalLink size={14} />
              </a>
              <a
                href="https://celo.org/climate"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-7 py-3.5 border border-teal/30 text-teal font-body font-medium rounded-sm hover:border-teal/60 transition-all duration-200"
              >
                Celo Climate Collective
                <ExternalLink size={14} />
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* ─── WAITLIST ─────────────────────────────────────────── */}
      <section id="waitlist" className="py-24 bg-navy">
        <div className="container">
          <div className="max-w-2xl mx-auto">
            <div className="text-center mb-12">
              <div className="section-label mb-3">Early Access</div>
              <h2 className="font-display text-4xl md:text-5xl font-bold text-white mb-4">
                Join the <span className="text-teal">WeSolar Waitlist</span>
              </h2>
              <p className="font-body text-white/70 text-lg leading-relaxed">
                WeSolar is currently in development. Join the waitlist to be notified when we launch in your area, get early access to fractional panel ownership, and help shape the platform through our community governance process.
              </p>
            </div>

            {submitted ? (
              <div className="text-center p-10 bg-[oklch(0.16_0.05_265)] border border-teal/30 rounded-sm">
                <CheckCircle2 size={48} className="text-teal mx-auto mb-4" />
                <h3 className="font-display text-2xl font-bold text-white mb-2">You're on the list.</h3>
                <p className="font-body text-white/60">We'll notify you when WeSolar launches in your area. In the meantime, explore the smart contracts on GitHub.</p>
                <a
                  href="https://github.com/ModernDigitalDevelopment/wesolar"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 mt-6 text-teal font-body font-medium hover:gap-3 transition-all duration-200"
                >
                  <Github size={16} />
                  Explore the GitHub repo
                  <ArrowRight size={14} />
                </a>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="bg-[oklch(0.16_0.05_265)] border border-white/10 rounded-sm p-8">
                <div className="grid sm:grid-cols-2 gap-4 mb-4">
                  <div>
                    <label className="block font-mono-data text-xs text-white/50 uppercase tracking-wider mb-2">
                      First Name (optional)
                    </label>
                    <input
                      type="text"
                      value={firstName}
                      onChange={(e) => setFirstName(e.target.value)}
                      placeholder="Your first name"
                      className="w-full bg-[oklch(0.12_0.05_265)] border border-white/20 rounded-sm px-4 py-3 text-white font-body text-sm placeholder:text-white/30 focus:outline-none focus:border-teal/50 transition-colors"
                    />
                  </div>
                  <div>
                    <label className="block font-mono-data text-xs text-white/50 uppercase tracking-wider mb-2">
                      Email Address *
                    </label>
                    <input
                      type="email"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      placeholder="your@email.com"
                      required
                      className="w-full bg-[oklch(0.12_0.05_265)] border border-white/20 rounded-sm px-4 py-3 text-white font-body text-sm placeholder:text-white/30 focus:outline-none focus:border-teal/50 transition-colors"
                    />
                  </div>
                </div>
                <button
                  type="submit"
                  disabled={subscribe.isPending || !email}
                  className="w-full flex items-center justify-center gap-2 px-7 py-3.5 bg-teal text-[oklch(0.12_0.05_265)] font-semibold font-body rounded-sm hover:bg-teal/90 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {subscribe.isPending ? "Joining..." : "Join the WeSolar Waitlist"}
                  {!subscribe.isPending && <ArrowRight size={16} />}
                </button>
                <p className="text-center font-body text-xs text-white/30 mt-4">
                  No spam. No selling your data. Just updates when WeSolar launches in your area.
                </p>
              </form>
            )}
          </div>
        </div>
      </section>

      {/* ─── CTA ──────────────────────────────────────────────── */}
      <section className="py-16 bg-[oklch(0.14_0.05_265)] border-t border-white/10">
        <div className="container">
          <div className="flex flex-col md:flex-row items-center justify-between gap-8">
            <div>
              <h3 className="font-display text-2xl font-bold text-white mb-2">Explore All Our Projects</h3>
              <p className="font-body text-white/60">WeSolar is one piece of the Elevation Foundation's ecosystem.</p>
            </div>
            <div className="flex flex-col sm:flex-row gap-4">
              <Link
                href="/our-work"
                className="inline-flex items-center gap-2 px-6 py-3 border border-white/30 text-white font-body font-medium rounded-sm hover:border-teal/50 hover:text-teal transition-all duration-200"
              >
                All Projects <ArrowRight size={14} />
              </Link>
              <Link
                href="/for-funders"
                className="inline-flex items-center gap-2 px-6 py-3 bg-gold/10 border border-gold/30 text-gold font-body font-medium rounded-sm hover:bg-gold/20 transition-all duration-200"
              >
                <TrendingUp size={14} />
                For Funders & Grantors
              </Link>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
